### ISSUE TITLE
Add explanation to the project's README the rules for editing

### ISSUE THREAD

**Issue by dixonsiu** [personium/personium.github.io#7]
Questions to be answer:
1. Who is responsible for running the Pandoc command?
1. What template or filter should be running with Pandoc command?

        <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
        <html xmlns="http://www.w3.org/1999/xhtml">
        <head>
          <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
          <meta http-equiv="Content-Style-Type" content="text/css" />
          <meta name="generator" content="pandoc" />
          <title></title>
          <style type="text/css">code{white-space: pre;}</style>
          <link rel="stylesheet" href="../github.css" type="text/css" />
        </head>

Plus the following rules:
1. Edit markdown file (see example) with relative path  
1. Link refer to markdown file can automatically converted to link to HTML file

**Comment by dixonsiu** [comment]
Basic solution to Q2 is [here](https://gist.github.com/dixonsiu/28c473f93722e586e6d53b035923967c).  
Need to add information on meta/CSS template to Pandoc command.

**Comment by KourokiTakuto** [comment]
Answer on Q2

The format specifies markdown_github.
As mentioned above, the filter creates and specifies convertlink.py at the link destination.
CSS specifies github.css with the -c option.

The command satisfying the above is as follows.

```
Pandoc -s -f markdown_github --filter=convertlink.py xxxx.md - c github.css - o xxxx.html
```

Although it is converted to an HTML file by the above command, it is necessary to pay attention to the following.

If there is a table to be converted, tags are created automatically as \<table style = "width: 28%;"\>.
If you specify width, the table display will be incorrect, so you need to convert it to \<table\>.

**Comment by dixonsiu** [comment]
Even when running in Windows, we want to use the "/" correctly so that the href will work correctly in Linux.
Following is the example when executed in document-writer directory.  

    pandoc -s -f markdown_github --filter=../../../convertLink.py -c ../github.css README.md -o index.html

**Comment by dixonsiu** [comment]
wrote a [script](https://gist.github.com/dixonsiu/28f1001df901783c507b78953f4aa3ec) that traverse the directory and convert md files

**Comment by dixonsiu** [comment]
[Latest command](https://gist.github.com/dixonsiu/2b98aed52f2f4106f74af8978fc8245b) for automation requires the followings.

1. Write special itemized list in HTML format in markdown file.  
[Sample changes](8d6d9303b950a7188fd3c9cb646cdb6ef51b15fb) that I applied for English version. UL tag uses a special CSS class to hide the "bullet".  

        <ul class="listStyleTypeNone">

1. Unfortunately, table conversion still needs to do it manually.
